"""Desktop launchers: a clickable way into the dashboard.

A LAUNCHER, NOT A SECOND IMPLEMENTATION. Everything here creates a file whose
only job is to run ``agent-switch web``. There is no separate app, no bundled
runtime and no duplicated logic, so the CLI, the TUI and a headless
``agent-switch web --no-open`` over SSH keep working exactly as they did. On a
machine with no desktop you simply never install one.

Content generation is split from the filesystem work on purpose. The previous
platform-specific code in this project (the Windows process scan) was written so
that it could only run on the platform it targeted, and therefore went untested
everywhere else until it was found to be broken. Every launcher's text is built
by a pure function that runs on any OS, so all three are covered by the suite
wherever it runs.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

APP_NAME = "agent-switch"
DISPLAY_NAME = "agent-switch"
BUNDLE_ID = "dev.agentswitch.dashboard"


@dataclass(frozen=True)
class LauncherPlan:
    """What installing would create: one or more files, and how to describe it."""

    paths: tuple[Path, ...]
    description: str
    supported: bool = True
    reason: str = ""


def executable_path() -> str:
    """Absolute path of the ``agent-switch`` command.

    Resolved next to the running interpreter FIRST, because that is where an
    isolated install (``uv tool install``, a venv) puts the console script, and
    a launcher must not depend on the desktop session having the same PATH the
    terminal does -- it will not.
    """
    suffix = ".exe" if sys.platform == "win32" else ""
    candidate = Path(sys.executable).parent / f"{APP_NAME}{suffix}"
    if candidate.exists():
        return str(candidate)
    found = shutil.which(APP_NAME)
    if found:
        return str(Path(found).resolve())
    # Last resort: re-enter through the interpreter, which always exists.
    return f"{sys.executable} -m claude_swap.cli"


# -- content builders (pure; tested on every platform) -------------------

def macos_launch_script(executable: str) -> str:
    """The shell script inside the .app bundle.

    ``exec`` so the bundle's process IS the server rather than its parent:
    quitting the app then actually stops the dashboard instead of orphaning it.
    """
    return (
        "#!/bin/sh\n"
        "# Generated by `agent-switch app install`. Safe to delete.\n"
        f'exec {_shell_quote(executable)} web\n'
    )


def macos_info_plist() -> str:
    """Minimal Info.plist. ``LSBackgroundOnly`` is deliberately NOT set: the
    dashboard opens a browser and the user should see the app in the Dock so
    there is an obvious way to quit it."""
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>{DISPLAY_NAME}</string>
  <key>CFBundleDisplayName</key><string>{DISPLAY_NAME}</string>
  <key>CFBundleIdentifier</key><string>{BUNDLE_ID}</string>
  <key>CFBundleExecutable</key><string>{APP_NAME}</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
"""


def linux_desktop_entry(executable: str) -> str:
    """A freedesktop .desktop entry.

    ``Terminal=false`` because the dashboard's interface is the browser; the
    terminal output is just the URL, which it opens itself.
    """
    return (
        "[Desktop Entry]\n"
        "Type=Application\n"
        f"Name={DISPLAY_NAME}\n"
        "Comment=Switch Claude Code and Codex accounts\n"
        f"Exec={executable} web\n"
        "Terminal=false\n"
        "Categories=Utility;Development;\n"
        "StartupNotify=false\n"
    )


def windows_shortcut_script(executable: str, shortcut: Path) -> str:
    """PowerShell that creates a .lnk.

    A real shortcut needs COM, and PowerShell is the one way to reach it that
    is always present -- pywin32 would be a dependency bought for one file.
    """
    return (
        "$s = (New-Object -ComObject WScript.Shell)."
        f"CreateShortcut('{shortcut}')\n"
        f"$s.TargetPath = '{executable}'\n"
        "$s.Arguments = 'web'\n"
        f"$s.WorkingDirectory = '{Path(executable).parent}'\n"
        f"$s.Description = 'Switch Claude Code and Codex accounts'\n"
        "$s.Save()\n"
    )


def _shell_quote(value: str) -> str:
    return "'" + value.replace("'", "'\\''") + "'"


# -- locations ----------------------------------------------------------

def macos_app_path() -> Path:
    """``~/Applications`` rather than ``/Applications``: no sudo, and it is
    per-user state like everything else this tool writes."""
    return Path.home() / "Applications" / f"{DISPLAY_NAME}.app"


def linux_desktop_path() -> Path:
    data_home = os.environ.get("XDG_DATA_HOME") or str(Path.home() / ".local" / "share")
    return Path(data_home) / "applications" / f"{APP_NAME}.desktop"


def windows_shortcut_path() -> Path:
    appdata = os.environ.get("APPDATA") or str(Path.home() / "AppData" / "Roaming")
    return (
        Path(appdata) / "Microsoft" / "Windows" / "Start Menu" / "Programs"
        / f"{DISPLAY_NAME}.lnk"
    )


def plan(platform: str | None = None) -> LauncherPlan:
    """What ``install`` would create on this platform."""
    platform = platform or sys.platform
    if platform == "darwin":
        return LauncherPlan((macos_app_path(),),
                            "an app bundle in ~/Applications (Spotlight-searchable)")
    if platform == "win32":
        return LauncherPlan((windows_shortcut_path(),),
                            "a Start Menu shortcut")
    if platform.startswith("linux"):
        return LauncherPlan((linux_desktop_path(),),
                            "a desktop entry in your applications menu")
    return LauncherPlan((), "", supported=False,
                        reason=f"no desktop launcher is defined for {platform}")


# -- install / uninstall ------------------------------------------------

def install(platform: str | None = None) -> LauncherPlan:
    """Create the launcher, replacing any previous one.

    Raises:
        OSError: The launcher could not be written.
    """
    platform = platform or sys.platform
    target = plan(platform)
    if not target.supported:
        return target
    executable = executable_path()

    if platform == "darwin":
        app = macos_app_path()
        macos = app / "Contents" / "MacOS"
        macos.mkdir(parents=True, exist_ok=True)
        (app / "Contents" / "Info.plist").write_text(macos_info_plist(), encoding="utf-8")
        script = macos / APP_NAME
        script.write_text(macos_launch_script(executable), encoding="utf-8")
        script.chmod(0o755)
        # Without this the Finder can keep showing a stale name or icon for a
        # bundle that has been rewritten in place.
        subprocess.run(["touch", str(app)], capture_output=True, check=False)
    elif platform.startswith("linux"):
        entry = linux_desktop_path()
        entry.parent.mkdir(parents=True, exist_ok=True)
        entry.write_text(linux_desktop_entry(executable), encoding="utf-8")
        entry.chmod(0o755)
    elif platform == "win32":  # pragma: no cover - exercised on Windows only
        shortcut = windows_shortcut_path()
        shortcut.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run(
            ["powershell", "-NoProfile", "-NonInteractive", "-Command",
             windows_shortcut_script(executable, shortcut)],
            capture_output=True, check=False, timeout=30,
        )
    return target


def uninstall(platform: str | None = None) -> list[Path]:
    """Remove the launcher. Returns what was actually removed."""
    platform = platform or sys.platform
    removed: list[Path] = []
    for path in plan(platform).paths:
        try:
            if path.is_dir():
                shutil.rmtree(path)
            else:
                path.unlink()
            removed.append(path)
        except FileNotFoundError:
            continue
        except OSError:
            continue
    return removed


def is_installed(platform: str | None = None) -> bool:
    target = plan(platform)
    return bool(target.paths) and all(p.exists() for p in target.paths)
